### ISSUE TITLE
need to add async_timeout to dependency

### ISSUE THREAD

**Issue by jkh911208** [bretterer/rivian-python-client#82]
Hi, thank you for amazing package

i noticed you are missing the async_timeout as dependency, so your package is giving me exception out of the box.
I am not familiar with how you manage the dependency, so i cannot raise the PR, but i am sure it is simple enough fix

Thank you!

**Comment by natekspencer** [comment]
Thanks for the catch! It looks like async_timeout is only needed for python < 3.11, so I'll add some checks for that

**Comment by natekspencer** [comment]
This has been addressed in [Release 1.2.0](https://github.com/bretterer/rivian-python-client/releases/tag/1.2.0)
